name: Traviskellerman
favicon: null
layout_spectrum: 0.22804
typography_spectrum: 0.26787
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#afd5aa'
    - '#558989'
    - '#00385c'
    - '#006577'
  brandStrength: 0.816773941507563
  lightness: 0.1875
  saturation: 0.12829113914631307
  rhythmicContrast: 0
purpose: []
